# store your development credentials for spring app here
# this file should and will not be checked into version control
staffjoy:
  common:
    sentry-dsn: https://80bb246@sentry.io/1271087
  signing-secret: 6125757p
  intercom-access-token: xjc
  aliyun-access-key: LTA
  aliyun-access-secret: y
  aliyun-sms-sign-name: staffjoy
  intercom-app-id: xjc
  intercom-signing-secret: 6125757p
  recaptcha-public: xjc
  recaptcha-private: xjc
